name: Update M3U8

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt-get install -y jq
      
      - name: Run proxy generator
        run: |
          python proxy.py
          cat youtube_1080p.m3u8
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add youtube_1080p.m3u8
          git commit -m "Auto-update M3U8 $(date +'%Y-%m-%d %H:%M')" || true
          git push

      - name: Notify on failure
        if: failure()
        uses: actions/telegram@v1
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          text: "YouTube 1080P 更新失败！"
