jobs:
  update:
    steps:
      # ...原有步骤...
      name: Update M3U8

on:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次
  workflow_dispatch:        # 手动触发

on:
  workflow_dispatch:
    inputs:
      resolution:
        description: '目标分辨率'
        required: true
        default: '1080p'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install yt-dlp
          sudo apt-get install -y jq
      
      - name: Generate M3U8
        run: |
          python proxy.py
          touch .nojekyll
          echo "include: ['*.m3u8']" > _config.yml
      
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .nojekyll _config.yml youtube_1080p.m3u8
          git commit -m "Auto-update $(date +'%Y-%m-%d %H:%M')" || true
          git push
          
      - name: Notify on success
        if: success()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ M3U8 更新成功！访问地址：\nhttps://raw.githubusercontent.com/${{ github.repository }}/main/youtube_1080p.m3u8'
            })

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ 更新失败！请检查 [Action日志](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
            })

            on:
  workflow_dispatch:
    inputs:
      resolution:
        description: '目标分辨率'
        required: true
        default: '1080p'
